spring.datasource.url=jdbc:mysql://localhost:3306/music_league
spring.datasource.username=root
spring.datasource.password=sk3@thC^7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080